### ISSUE TITLE
Prototype I - Progress tracker

### ISSUE THREAD

**Issue by BaerMitUmlaut** [Soil/Soil#12]
# Prototype I
Working foundation with prototypes of core functionality.
- [x] Solid folder structure
- [x] Setup and build scripts
- [x] Core component running, with working custom compilation of functions
- [x] Prototype of objectives component, able to create and manage objectives
- [x] Prototype of spawning component, able to spawn a simple group at a given objective
